name: skillset
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^1.0.0+8
  at_server_status: ^0.1.0+1
  at_demo_data: ^0.0.3+1
  cached_network_image: ^2.5.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.2+1
  path_provider: ^2.0.1
  provider: ^5.0.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf
