name: skillset
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf
